default:
  image: python:3.9

stages:
  - test
  - publish

before_script:
  - echo "This is the before script"
  - pip install twine

testing:
  stage: test
  script:
    - echo "This is the test stage"

publishing:
  stage: publish
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
    - when: manual
  script:
    - echo "This is the publish stage"
    - python setup.py sdist
    - echo "Build done..."
    - twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi -u gitlab-ci-token -p "$CI_JOB_TOKEN" dist/*
    - echo "Publish done..."
